-- Create table to store contact form messages
CREATE TABLE public.contact_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  name text,
  email text NOT NULL,
  company text,
  message text NOT NULL,
  status text DEFAULT 'new'::text, -- e.g., 'new', 'read', 'replied'
  admin_reply text -- To store admin replies later
);

-- Optional: Enable Row Level Security (Recommended)
-- Policies will be needed later for admin access
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

-- Allow public insert access (anyone can submit the form)
-- Drop the existing policy first if it exists, to avoid errors on re-run
DROP POLICY IF EXISTS "Allow public insert access" ON public.contact_messages; 
-- Create the policy explicitly for the 'public' role (includes anon)
CREATE POLICY "Allow public insert access" ON public.contact_messages
  FOR INSERT
  TO public -- Use public instead of anon
  WITH CHECK (true);

-- Add comments for clarity
COMMENT ON TABLE public.contact_messages IS 'Stores messages submitted via the contact form.';
COMMENT ON COLUMN public.contact_messages.status IS 'Tracks the status of the message (e.g., new, read, replied).';
COMMENT ON COLUMN public.contact_messages.admin_reply IS 'Stores the reply sent by an admin.';
