name: Sync to Public Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to ensure proper syncing

      - name: Set up Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to public repository
        run: |
          # Add the public repository as a remote
          git remote add public https://${{ secrets.SYNC_TOKEN }}@github.com/baip-ai/baip-ai.github.io.git
          
          # Push to the public repository's main branch
          git push public main:main --force
        env:
          SYNC_TOKEN: ${{ secrets.SYNC_TOKEN }}
